definition:
  task:
    overwrite:
      module: src.client.TaskClient
      parameters:
        controller_address: "http://localhost:5020/api"
    import: ../tasks/task_assembly.yaml
  agent:
    import:
      - ../agents/api_agents_gigachat.yaml
      - ../agents/fs_agent.yaml